# Generated by Django 4.2.7 on 2023-11-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_planner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.CharField(max_length=100)),
                ('heading', models.CharField(max_length=30)),
            ],
        ),
    ]
