# Generated by Django 4.2.4 on 2025-04-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_daily_planner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_planner',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
